# Generated by Django 5.2.3 on 2025-07-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_alter_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(null=True, upload_to='topic_images/'),
        ),
    ]
