# Generated by Django 5.2.3 on 2025-07-09 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_commentvote_topicvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='vote_count',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='vote_count',
        ),
        migrations.AlterField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='communities.topic'),
        ),
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together={('comment', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='topicvote',
            unique_together={('topic', 'user')},
        ),
    ]
