# Generated by Django 5.2.3 on 2025-07-09 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_remove_comment_vote_count_remove_topic_vote_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
