# Generated by Django 5.2.3 on 2025-07-28 12:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0012_remove_topic_view_count_communityclick_topicclick'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together={('user', 'community')},
        ),
    ]
