# Generated by Django 5.2.3 on 2025-07-28 13:40

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0013_alter_subscriber_unique_together'),
    ]

    operations = [
        VectorExtension(),
    ]
