# Generated by Django 5.2.3 on 2025-07-29 08:12

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0014_auto_20250728_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='interest_vector',
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='weighted_sum_vector',
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
